/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Recruitment;

import CA.AC;
import CMS.DB;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author panha
 */
public class frm_insertAll_single extends javax.swing.JFrame {
    DB c = new DB();
    String Sql=null;
    AC ac = new AC();
    DefaultTableModel model_skill,model_postion,model_studytype,
            model_traincousre,model_major,model_emtype,model_dept,model_cate,model_traintype;
    JTextField txtdpid = new JTextField();
  
    
    /**
     * Creates new form frm_insertAll_single
     */
    public frm_insertAll_single() {
        initComponents(); 
        Display();
    }
    
    private  void INSERT_TO_ACCESS(){
        ac.Query("INSERT INTO DEPARTMENTS\n" +
                 "(DEPTNAME, DEPTID)\n" +
                  "VALUES('"+txtDept_name.getText()+"', "+txtdpid.getText()+");");
    }
    
   private  void UPDATE_TO_ACCESS(){
        ac.Query("UPDATE DEPARTMENTS\n" +
                    "SET DEPTNAME='"+txtDept_name.getText()+"'\n" +
                    "WHERE DEPTID="+txtDept_id.getText()+";");
    }
    
    private  void DELETE_TO_ACCESS(){
        ac.Query("DELETE * FROM DEPARTMENTS WHERE DEPTID="+txtDept_id.getText()+";");
    }
    
    
    
    private void Display(){
        Show_Data(tbskill, "skills", model_skill);
        Show_Data(tbcate, "categorys", model_cate);
        Show_Data(tbposition,"positions" , model_postion);
        Show_Data(tbdept, "departments", model_dept);
        Show_Data(tbemtype, "emptype", model_emtype);
        Show_Data(tbmajor,  "majors", model_major);
        Show_Data(tbtraincourse, "trainingcoursetypes", model_traincousre);
        Show_Data(tbStudyrecordtype, "studyrecordtypes", model_studytype);
        ShowID("skills","SkillID",txtSkill_id);
        ShowID("Positions", "PositionID",txtPosition_id);
        ShowID("departments", "DepartmentId",txtDept_id);
        ShowID("emptype", "EmpTypeId",txtEmtype_id);
        ShowID("studyrecordtypes", "StudyRecordTypeId",txtStudyrecordtype_id);
        ShowID("majors", "MajorId",txtMajor_id);
        ShowID("categorys", "CatId",txtCate_id);
        ShowID("trainingcoursetypes", "TrainingCourseTypeId",txtTraincourse_id);
        c.showDataInTable(tbTrainType, "SELECT * FROM trainingtypes", model_traintype);
        ShowID("trainingtypes", "TrainingTypeID", txtTrainTypeID);
        
      
    }
    
    void Insert_Data(String table , String field,JTextField txtname){
        Sql = "INSERT INTO "+table+" ("+field+") VALUES('"+txtname.getText()+"')";
        c.Query(Sql);
    }
    void Update_Data(String table , String field ,String update, String fieldID, String id){
        Sql="UPDATE "+table+" SET "+field+"='"+update+"' WHERE "+fieldID+" = '"+id+"' ";
        c.Query(Sql);
    }
    void Delete_Data(String table , String fieldname ,String id){
        Sql="DELETE FROM "+table+" WHERE "+fieldname+" = '"+id+"' ";
        c.Query(Sql);
    }
    void Show_Data(JTable tb,String table ,DefaultTableModel model){
        Sql="SELECT * FROM "+table+"";
        c.showDataInTable(tb, Sql, model);
    }
    
    void ShowID(String tbname , String colname , JTextField txt){
        Sql="SELECT MAX("+colname+") FROM "+tbname+";";
        c.Value_ID(Sql, txt);
    }
    
    void SelectedTable(JTable tb ,JTextField txtid,JTextField txtname){
        int i = tb.getSelectedRow();
        TableModel m = tb.getModel();
        txtid.setText(m.getValueAt(i, 0).toString());
        txtname.setText(m.getValueAt(i, 1).toString());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbpall = new javax.swing.JTabbedPane();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        tbposition = new javax.swing.JTable();
        btnaddpostion = new javax.swing.JButton();
        btnupdatepostion = new javax.swing.JButton();
        btndeleteposition = new javax.swing.JButton();
        txtPosition_name = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtPosition_id = new javax.swing.JTextField();
        jDesktopPane3 = new javax.swing.JDesktopPane();
        jScrollPane8 = new javax.swing.JScrollPane();
        tbemtype = new javax.swing.JTable();
        btnaddemtype = new javax.swing.JButton();
        btnupdateemtype = new javax.swing.JButton();
        btndeleteemtype = new javax.swing.JButton();
        txtEmtype_name = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtEmtype_id = new javax.swing.JTextField();
        jDesktopPane4 = new javax.swing.JDesktopPane();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbStudyrecordtype = new javax.swing.JTable();
        btnadd_Studyrecordtype = new javax.swing.JButton();
        btnupdate_Studyrecordtype = new javax.swing.JButton();
        btndelete_Studyrecordtype = new javax.swing.JButton();
        txtStudyrecordtype_name = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtStudyrecordtype_id = new javax.swing.JTextField();
        jDesktopPane5 = new javax.swing.JDesktopPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbtraincourse = new javax.swing.JTable();
        btnadd_traincourse = new javax.swing.JButton();
        btnupdate_traincourse = new javax.swing.JButton();
        btndelete_traincourse = new javax.swing.JButton();
        txtTraincourse_name = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTraincourse_id = new javax.swing.JTextField();
        jDesktopPane6 = new javax.swing.JDesktopPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbcate = new javax.swing.JTable();
        btnadd_cate = new javax.swing.JButton();
        btnupdate_cate = new javax.swing.JButton();
        btndelete_cate = new javax.swing.JButton();
        txtCate_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCate_id = new javax.swing.JTextField();
        jDesktopPane7 = new javax.swing.JDesktopPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbmajor = new javax.swing.JTable();
        btnadd_major = new javax.swing.JButton();
        btnupdate_major = new javax.swing.JButton();
        btndelete_major = new javax.swing.JButton();
        txtMajor_name = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMajor_id = new javax.swing.JTextField();
        jDesktopPane9 = new javax.swing.JDesktopPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdept = new javax.swing.JTable();
        btnadd_dept = new javax.swing.JButton();
        btnupdate_dept = new javax.swing.JButton();
        btndelete_dept = new javax.swing.JButton();
        txtDept_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDept_id = new javax.swing.JTextField();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSkill_id = new javax.swing.JTextField();
        txtSkill_name = new javax.swing.JTextField();
        btnadd_skill = new javax.swing.JButton();
        btnupdate_skill = new javax.swing.JButton();
        btndelete_skill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbskill = new javax.swing.JTable();
        jDesktopPane8 = new javax.swing.JDesktopPane();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtTrainTypeID = new javax.swing.JTextField();
        txtTrainTypeName = new javax.swing.JTextField();
        txtTrainTypeDura = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtTrainDes = new javax.swing.JTextArea();
        btnAddTrainType = new javax.swing.JButton();
        btnUpdateTrainType = new javax.swing.JButton();
        btnDeleteTrainType = new javax.swing.JButton();
        jScrollPane10 = new javax.swing.JScrollPane();
        tbTrainType = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbpall.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jDesktopPane2.setBackground(new java.awt.Color(255, 255, 255));

        tbposition.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbposition.setRowHeight(20);
        tbposition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpositionMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tbposition);

        btnaddpostion.setText("Add");
        btnaddpostion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddpostionActionPerformed(evt);
            }
        });

        btnupdatepostion.setText("Update");
        btnupdatepostion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatepostionActionPerformed(evt);
            }
        });

        btndeleteposition.setText("Delete");
        btndeleteposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletepositionActionPerformed(evt);
            }
        });

        txtPosition_name.setText("jTextField1");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Name :");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("ID :");

        txtPosition_id.setText("jTextField1");

        jDesktopPane2.setLayer(jScrollPane9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnaddpostion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btnupdatepostion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(btndeleteposition, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txtPosition_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane2.setLayer(txtPosition_id, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPosition_id, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPosition_name, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDesktopPane2Layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(btnaddpostion, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btnupdatepostion, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(btndeleteposition, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPosition_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPosition_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnaddpostion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdatepostion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndeleteposition, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        tbpall.addTab("Position", jDesktopPane2);

        jDesktopPane3.setBackground(new java.awt.Color(255, 255, 255));

        tbemtype.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbemtype.setRowHeight(20);
        tbemtype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbemtypeMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tbemtype);

        btnaddemtype.setText("Add");
        btnaddemtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddemtypeActionPerformed(evt);
            }
        });

        btnupdateemtype.setText("Update");
        btnupdateemtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateemtypeActionPerformed(evt);
            }
        });

        btndeleteemtype.setText("Delete");
        btndeleteemtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteemtypeActionPerformed(evt);
            }
        });

        txtEmtype_name.setText("jTextField1");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Name :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("ID :");

        txtEmtype_id.setText("jTextField1");

        jDesktopPane3.setLayer(jScrollPane8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(btnaddemtype, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(btnupdateemtype, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(btndeleteemtype, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(txtEmtype_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane3.setLayer(txtEmtype_id, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane3Layout = new javax.swing.GroupLayout(jDesktopPane3);
        jDesktopPane3.setLayout(jDesktopPane3Layout);
        jDesktopPane3Layout.setHorizontalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEmtype_id, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtEmtype_name, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnaddemtype, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btnupdateemtype, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btndeleteemtype, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDesktopPane3Layout.setVerticalGroup(
            jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmtype_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmtype_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jDesktopPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnaddemtype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdateemtype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndeleteemtype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpall.addTab("EmployeeType", jDesktopPane3);

        jDesktopPane4.setBackground(new java.awt.Color(255, 255, 255));

        tbStudyrecordtype.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbStudyrecordtype.setRowHeight(20);
        tbStudyrecordtype.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbStudyrecordtypeMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tbStudyrecordtype);

        btnadd_Studyrecordtype.setText("Add");
        btnadd_Studyrecordtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd_StudyrecordtypeActionPerformed(evt);
            }
        });

        btnupdate_Studyrecordtype.setText("Update");
        btnupdate_Studyrecordtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate_StudyrecordtypeActionPerformed(evt);
            }
        });

        btndelete_Studyrecordtype.setText("Delete");
        btndelete_Studyrecordtype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete_StudyrecordtypeActionPerformed(evt);
            }
        });

        txtStudyrecordtype_name.setText("jTextField1");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Name :");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("ID :");

        txtStudyrecordtype_id.setText("jTextField1");

        jDesktopPane4.setLayer(jScrollPane7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(btnadd_Studyrecordtype, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(btnupdate_Studyrecordtype, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(btndelete_Studyrecordtype, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(txtStudyrecordtype_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane4.setLayer(txtStudyrecordtype_id, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane4Layout = new javax.swing.GroupLayout(jDesktopPane4);
        jDesktopPane4.setLayout(jDesktopPane4Layout);
        jDesktopPane4Layout.setHorizontalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtStudyrecordtype_id, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtStudyrecordtype_name, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnadd_Studyrecordtype, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btnupdate_Studyrecordtype, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btndelete_Studyrecordtype, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDesktopPane4Layout.setVerticalGroup(
            jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudyrecordtype_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStudyrecordtype_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jDesktopPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadd_Studyrecordtype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate_Studyrecordtype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete_Studyrecordtype, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpall.addTab("StudyRecordType", jDesktopPane4);

        jDesktopPane5.setBackground(new java.awt.Color(255, 255, 255));

        tbtraincourse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbtraincourse.setRowHeight(20);
        tbtraincourse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtraincourseMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbtraincourse);

        btnadd_traincourse.setText("Add");
        btnadd_traincourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd_traincourseActionPerformed(evt);
            }
        });

        btnupdate_traincourse.setText("Update");
        btnupdate_traincourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate_traincourseActionPerformed(evt);
            }
        });

        btndelete_traincourse.setText("Delete");
        btndelete_traincourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete_traincourseActionPerformed(evt);
            }
        });

        txtTraincourse_name.setText("jTextField1");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Name :");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("ID :");

        txtTraincourse_id.setText("jTextField1");

        jDesktopPane5.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(btnadd_traincourse, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(btnupdate_traincourse, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(btndelete_traincourse, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(txtTraincourse_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane5.setLayer(txtTraincourse_id, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane5Layout = new javax.swing.GroupLayout(jDesktopPane5);
        jDesktopPane5.setLayout(jDesktopPane5Layout);
        jDesktopPane5Layout.setHorizontalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTraincourse_id, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTraincourse_name, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnadd_traincourse, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btnupdate_traincourse, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btndelete_traincourse, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDesktopPane5Layout.setVerticalGroup(
            jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTraincourse_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTraincourse_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jDesktopPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadd_traincourse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate_traincourse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete_traincourse, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpall.addTab("Trainingcoursetypes", jDesktopPane5);

        jDesktopPane6.setBackground(new java.awt.Color(255, 255, 255));

        tbcate.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbcate.setRowHeight(20);
        tbcate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbcateMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbcate);

        btnadd_cate.setText("Add");
        btnadd_cate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd_cateActionPerformed(evt);
            }
        });

        btnupdate_cate.setText("Update");
        btnupdate_cate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate_cateActionPerformed(evt);
            }
        });

        btndelete_cate.setText("Delete");
        btndelete_cate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete_cateActionPerformed(evt);
            }
        });

        txtCate_name.setText("jTextField1");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Name :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ID :");

        txtCate_id.setText("jTextField1");

        jDesktopPane6.setLayer(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(btnadd_cate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(btnupdate_cate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(btndelete_cate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(txtCate_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane6.setLayer(txtCate_id, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane6Layout = new javax.swing.GroupLayout(jDesktopPane6);
        jDesktopPane6.setLayout(jDesktopPane6Layout);
        jDesktopPane6Layout.setHorizontalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCate_id, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCate_name, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnadd_cate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btnupdate_cate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btndelete_cate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDesktopPane6Layout.setVerticalGroup(
            jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCate_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCate_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jDesktopPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadd_cate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate_cate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete_cate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpall.addTab("Categorys", jDesktopPane6);

        jDesktopPane7.setBackground(new java.awt.Color(255, 255, 255));

        tbmajor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbmajor.setRowHeight(20);
        tbmajor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbmajorMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbmajor);

        btnadd_major.setText("Add");
        btnadd_major.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd_majorActionPerformed(evt);
            }
        });

        btnupdate_major.setText("Update");
        btnupdate_major.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate_majorActionPerformed(evt);
            }
        });

        btndelete_major.setText("Delete");
        btndelete_major.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete_majorActionPerformed(evt);
            }
        });

        txtMajor_name.setText("jTextField1");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Name :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("ID :");

        txtMajor_id.setText("jTextField1");

        jDesktopPane7.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane7.setLayer(btnadd_major, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane7.setLayer(btnupdate_major, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane7.setLayer(btndelete_major, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane7.setLayer(txtMajor_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane7.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane7.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane7.setLayer(txtMajor_id, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane7Layout = new javax.swing.GroupLayout(jDesktopPane7);
        jDesktopPane7.setLayout(jDesktopPane7Layout);
        jDesktopPane7Layout.setHorizontalGroup(
            jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane7Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMajor_id, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane7Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMajor_name, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane7Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnadd_major, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btnupdate_major, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btndelete_major, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDesktopPane7Layout.setVerticalGroup(
            jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMajor_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMajor_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jDesktopPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadd_major, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate_major, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete_major, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpall.addTab("Major", jDesktopPane7);

        jDesktopPane9.setBackground(new java.awt.Color(255, 255, 255));

        tbdept.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbdept.setRowHeight(20);
        tbdept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdeptMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbdept);

        btnadd_dept.setText("Add");
        btnadd_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd_deptActionPerformed(evt);
            }
        });

        btnupdate_dept.setText("Update");
        btnupdate_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate_deptActionPerformed(evt);
            }
        });

        btndelete_dept.setText("Delete");
        btndelete_dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete_deptActionPerformed(evt);
            }
        });

        txtDept_name.setText("jTextField1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Name :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ID :");

        txtDept_id.setText("jTextField1");

        jDesktopPane9.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane9.setLayer(btnadd_dept, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane9.setLayer(btnupdate_dept, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane9.setLayer(btndelete_dept, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane9.setLayer(txtDept_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane9.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane9.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane9.setLayer(txtDept_id, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane9Layout = new javax.swing.GroupLayout(jDesktopPane9);
        jDesktopPane9.setLayout(jDesktopPane9Layout);
        jDesktopPane9Layout.setHorizontalGroup(
            jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane9Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDept_id, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane9Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtDept_name, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane9Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnadd_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btnupdate_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btndelete_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDesktopPane9Layout.setVerticalGroup(
            jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane9Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDept_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDept_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jDesktopPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadd_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete_dept, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpall.addTab("Departments", jDesktopPane9);

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setAutoscrolls(true);
        jDesktopPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name :");

        txtSkill_id.setText("jTextField1");

        txtSkill_name.setText("jTextField1");

        btnadd_skill.setText("Add");
        btnadd_skill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd_skillActionPerformed(evt);
            }
        });

        btnupdate_skill.setText("Update");
        btnupdate_skill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdate_skillActionPerformed(evt);
            }
        });

        btndelete_skill.setText("Delete");
        btndelete_skill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelete_skillActionPerformed(evt);
            }
        });

        tbskill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbskill.setRowHeight(20);
        tbskill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbskillMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbskill);

        jDesktopPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtSkill_id, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(txtSkill_name, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnadd_skill, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btnupdate_skill, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(btndelete_skill, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSkill_id, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSkill_name, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(btnadd_skill, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btnupdate_skill, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(btndelete_skill, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSkill_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSkill_name, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnadd_skill, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnupdate_skill, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete_skill, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbpall.addTab("Skill", jDesktopPane1);

        jDesktopPane8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("        ID :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Trainning Type :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("      Description :");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("         Duration :");

        txtTrainDes.setColumns(20);
        txtTrainDes.setRows(5);
        jScrollPane3.setViewportView(txtTrainDes);

        btnAddTrainType.setText("Add");

        btnUpdateTrainType.setText("Update");

        btnDeleteTrainType.setText("Delete");

        tbTrainType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbTrainType.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTrainTypeMouseClicked(evt);
            }
        });
        jScrollPane10.setViewportView(tbTrainType);

        jDesktopPane8.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(jLabel20, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(txtTrainTypeID, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(txtTrainTypeName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(txtTrainTypeDura, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(btnAddTrainType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(btnUpdateTrainType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(btnDeleteTrainType, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane8.setLayer(jScrollPane10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane8Layout = new javax.swing.GroupLayout(jDesktopPane8);
        jDesktopPane8.setLayout(jDesktopPane8Layout);
        jDesktopPane8Layout.setHorizontalGroup(
            jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane8Layout.createSequentialGroup()
                .addGroup(jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jDesktopPane8Layout.createSequentialGroup()
                                .addGroup(jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3)
                                    .addComponent(txtTrainTypeName)
                                    .addComponent(txtTrainTypeID)))
                            .addGroup(jDesktopPane8Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTrainTypeDura, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addComponent(btnAddTrainType, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateTrainType, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteTrainType, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane8Layout.setVerticalGroup(
            jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTrainTypeID)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTrainTypeName)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDesktopPane8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(txtTrainTypeDura)))
                    .addGroup(jDesktopPane8Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jDesktopPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddTrainType, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdateTrainType, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteTrainType, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbpall.addTab("TrainingType", jDesktopPane8);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbpall)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(tbpall, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnadd_skillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd_skillActionPerformed
        Insert_Data("skills","Skill" ,txtSkill_name);
        Show_Data(tbskill, "skills", model_skill);
        ShowID("skills","SkillID",txtSkill_id);
    }//GEN-LAST:event_btnadd_skillActionPerformed

    private void btnupdate_skillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate_skillActionPerformed
        Update_Data("skills", "Skill", txtSkill_name.getText(), "SkillID", txtSkill_id.getText());
        Show_Data(tbskill, "skills", model_skill);
        ShowID("skills","SkillID",txtSkill_id);
    }//GEN-LAST:event_btnupdate_skillActionPerformed

    private void btndelete_skillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete_skillActionPerformed
        Delete_Data("skills", "SkillID", txtSkill_id.getText());
        Show_Data(tbskill, "skills", model_skill);
        ShowID("skills","SkillID",txtSkill_id);
    }//GEN-LAST:event_btndelete_skillActionPerformed

    private void tbskillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbskillMouseClicked
        SelectedTable(tbskill, txtSkill_id, txtSkill_name);
    }//GEN-LAST:event_tbskillMouseClicked

    private void btnadd_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd_deptActionPerformed
        Insert_Data("departments", "Department", txtDept_name);
        Show_Data(tbdept, "departments", model_dept);
        ShowID("departments","DepartmentId",txtDept_id);
        c.Value_ID(txtdpid);
        
        INSERT_TO_ACCESS();
    }//GEN-LAST:event_btnadd_deptActionPerformed

    private void btnupdate_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate_deptActionPerformed
        Update_Data("departments", "Department", txtDept_name.getText(), "DepartmentId", txtDept_id.getText());
        Show_Data(tbdept, "departments", model_dept);
        ShowID("departments","DepartmentId",txtDept_id);
        
        UPDATE_TO_ACCESS();
    }//GEN-LAST:event_btnupdate_deptActionPerformed

    private void btndelete_deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete_deptActionPerformed
        Delete_Data("departments", "DepartmentId", txtDept_id.getText());
        Show_Data(tbdept, "departments", model_dept);
        ShowID("departments","DepartmentId",txtDept_id);
        
        DELETE_TO_ACCESS();
    }//GEN-LAST:event_btndelete_deptActionPerformed

    private void tbdeptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdeptMouseClicked
         SelectedTable(tbdept, txtDept_id, txtDept_name);
    }//GEN-LAST:event_tbdeptMouseClicked

    private void btnadd_majorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd_majorActionPerformed
        Insert_Data("majors", "Major", txtMajor_name);
        Show_Data(tbmajor,  "majors", model_major);
        ShowID("majors", "MajorId",txtMajor_id);
        
    }//GEN-LAST:event_btnadd_majorActionPerformed

    private void btnupdate_majorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate_majorActionPerformed
        Update_Data("majors", "Major", txtMajor_name.getText(), "MajorId", txtMajor_id.getText());
        Show_Data(tbmajor,  "majors", model_major);
        ShowID("majors", "MajorId",txtMajor_id);
    }//GEN-LAST:event_btnupdate_majorActionPerformed

    private void btndelete_majorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete_majorActionPerformed
        Delete_Data("majors", "MajorId", txtMajor_id.getText());
        Show_Data(tbmajor,  "majors", model_major);
        ShowID("majors", "MajorId",txtMajor_id);
    }//GEN-LAST:event_btndelete_majorActionPerformed

    private void tbmajorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmajorMouseClicked
        SelectedTable(tbmajor,txtMajor_id, txtMajor_name);
    }//GEN-LAST:event_tbmajorMouseClicked

    private void btnadd_cateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd_cateActionPerformed
        Insert_Data("categorys", "CatName", txtCate_name);
        Show_Data(tbcate, "categorys", model_cate);
        ShowID("categorys", "CatId",txtCate_id);
    }//GEN-LAST:event_btnadd_cateActionPerformed

    private void btnupdate_cateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate_cateActionPerformed
        Update_Data("categorys", "CatName", txtCate_name.getText(), "CatId", txtCate_id.getText());
        Show_Data(tbcate, "categorys", model_cate);
        ShowID("categorys", "CatId",txtCate_id);
    }//GEN-LAST:event_btnupdate_cateActionPerformed

    private void btndelete_cateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete_cateActionPerformed
        Delete_Data("categorys", "CatId", txtCate_id.getText());
        Show_Data(tbcate, "categorys", model_cate);
        ShowID("categorys", "CatId",txtCate_id);
    }//GEN-LAST:event_btndelete_cateActionPerformed

    private void tbcateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcateMouseClicked
        SelectedTable(tbcate, txtCate_name, txtCate_id);
    }//GEN-LAST:event_tbcateMouseClicked

    private void btnadd_traincourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd_traincourseActionPerformed
        Insert_Data("trainingcoursetypes", "TrainingCourseType", txtTraincourse_name);
        Show_Data(tbtraincourse, "trainingcoursetypes", model_traincousre);
        ShowID("trainingcoursetypes", "TrainingCourseTypeId",txtTraincourse_id);
    }//GEN-LAST:event_btnadd_traincourseActionPerformed

    private void btnupdate_traincourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate_traincourseActionPerformed
        Update_Data("trainingcoursetypes", "TrainingCourseType", txtTraincourse_name.getText(),  "TrainingCourseTypeId", txtTraincourse_id.getText());
        Show_Data(tbtraincourse, "trainingcoursetypes", model_traincousre);
        ShowID("trainingcoursetypes", "TrainingCourseTypeId",txtTraincourse_id);
    }//GEN-LAST:event_btnupdate_traincourseActionPerformed

    private void btndelete_traincourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete_traincourseActionPerformed
        Delete_Data("trainingcoursetypes", "TrainingCourseTypeId", txtTraincourse_id.getText());
        Show_Data(tbtraincourse, "trainingcoursetypes", model_traincousre);
        ShowID("trainingcoursetypes", "TrainingCourseTypeId",txtTraincourse_id);
    }//GEN-LAST:event_btndelete_traincourseActionPerformed

    private void tbtraincourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtraincourseMouseClicked
        SelectedTable(tbtraincourse, txtTraincourse_name, txtTraincourse_id);
    }//GEN-LAST:event_tbtraincourseMouseClicked

    private void btnadd_StudyrecordtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd_StudyrecordtypeActionPerformed
        Insert_Data("studyrecordtypes", "StudyRecordType", txtStudyrecordtype_name);
        Show_Data(tbStudyrecordtype, "studyrecordtypes", model_studytype);
        ShowID("studyrecordtypes", "StudyRecordTypeId",txtStudyrecordtype_id);
    }//GEN-LAST:event_btnadd_StudyrecordtypeActionPerformed

    private void btnupdate_StudyrecordtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdate_StudyrecordtypeActionPerformed
        Update_Data("studyrecordtypes", "StudyRecordType", txtStudyrecordtype_name.getText(), "StudyRecordTypeId", txtStudyrecordtype_id.getText());
        Show_Data(tbStudyrecordtype, "studyrecordtypes", model_studytype);
        ShowID("studyrecordtypes", "StudyRecordTypeId",txtStudyrecordtype_id);
    }//GEN-LAST:event_btnupdate_StudyrecordtypeActionPerformed

    private void btndelete_StudyrecordtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelete_StudyrecordtypeActionPerformed
        Delete_Data("studyrecordtypes", "StudyRecordTypeId", txtStudyrecordtype_id.getText());
        Show_Data(tbStudyrecordtype, "studyrecordtypes", model_studytype);
        ShowID("studyrecordtypes", "StudyRecordTypeId",txtStudyrecordtype_id);
    }//GEN-LAST:event_btndelete_StudyrecordtypeActionPerformed

    private void tbStudyrecordtypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbStudyrecordtypeMouseClicked
        SelectedTable(tbStudyrecordtype, txtStudyrecordtype_name, txtStudyrecordtype_id);
    }//GEN-LAST:event_tbStudyrecordtypeMouseClicked

    private void btnaddemtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddemtypeActionPerformed
        Insert_Data("emptype", "EmpType", txtEmtype_name);
        Show_Data(tbemtype, "emptype", model_emtype);
        ShowID("emptype", "EmpTypeId",txtEmtype_id);
    }//GEN-LAST:event_btnaddemtypeActionPerformed

    private void btnupdateemtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateemtypeActionPerformed
        Update_Data("emptype", "EmpType", txtEmtype_name.getText(), "EmpTypeId", txtEmtype_id.getText());
        Show_Data(tbemtype, "emptype", model_emtype);
        ShowID("emptype", "EmpTypeId",txtEmtype_id);
    }//GEN-LAST:event_btnupdateemtypeActionPerformed

    private void btndeleteemtypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteemtypeActionPerformed
        Delete_Data("emptype", "EmpTypeId", txtEmtype_id.getText());
        Show_Data(tbemtype, "emptype", model_emtype);
        ShowID("emptype", "EmpTypeId",txtEmtype_id);
    }//GEN-LAST:event_btndeleteemtypeActionPerformed

    private void tbemtypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbemtypeMouseClicked
        SelectedTable(tbemtype, txtEmtype_name, txtEmtype_id);
    }//GEN-LAST:event_tbemtypeMouseClicked

    private void btnaddpostionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddpostionActionPerformed
        Insert_Data("positions", "Position", txtPosition_name);
        Show_Data(tbposition,"positions" , model_postion);
        ShowID("Positions", "PositionID",txtPosition_id);
    }//GEN-LAST:event_btnaddpostionActionPerformed

    private void btnupdatepostionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatepostionActionPerformed
        Update_Data("positions", "Position", txtPosition_name.getText(), "PositionID", txtPosition_id.getText());
        Show_Data(tbposition,"positions" , model_postion);
        ShowID("Positions", "PositionID",txtPosition_id);
    }//GEN-LAST:event_btnupdatepostionActionPerformed

    private void btndeletepositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletepositionActionPerformed
        Delete_Data("Positions", "PositionID", txtPosition_id.getText());
        Show_Data(tbposition,"positions" , model_postion);
        ShowID("Positions", "PositionID",txtPosition_id);
    }//GEN-LAST:event_btndeletepositionActionPerformed

    private void tbpositionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpositionMouseClicked
        SelectedTable(tbposition,txtPosition_name, txtPosition_id);
    }//GEN-LAST:event_tbpositionMouseClicked

    private void tbTrainTypeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTrainTypeMouseClicked
       int i = tbTrainType.getSelectedRow();
       TableModel m = tbTrainType.getModel();
       txtTrainTypeID.setText(m.getValueAt(i, 0).toString());
       txtTrainTypeName.setText(m.getValueAt(i, 1).toString());
       txtTrainDes.setText(m.getValueAt(i, 2).toString());
       txtTrainTypeDura.setText(m.getValueAt(i, 3).toString());
    }//GEN-LAST:event_tbTrainTypeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_insertAll_single.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_insertAll_single.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_insertAll_single.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_insertAll_single.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_insertAll_single().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTrainType;
    private javax.swing.JButton btnDeleteTrainType;
    private javax.swing.JButton btnUpdateTrainType;
    private javax.swing.JButton btnadd_Studyrecordtype;
    private javax.swing.JButton btnadd_cate;
    private javax.swing.JButton btnadd_dept;
    private javax.swing.JButton btnadd_major;
    private javax.swing.JButton btnadd_skill;
    private javax.swing.JButton btnadd_traincourse;
    private javax.swing.JButton btnaddemtype;
    private javax.swing.JButton btnaddpostion;
    private javax.swing.JButton btndelete_Studyrecordtype;
    private javax.swing.JButton btndelete_cate;
    private javax.swing.JButton btndelete_dept;
    private javax.swing.JButton btndelete_major;
    private javax.swing.JButton btndelete_skill;
    private javax.swing.JButton btndelete_traincourse;
    private javax.swing.JButton btndeleteemtype;
    private javax.swing.JButton btndeleteposition;
    private javax.swing.JButton btnupdate_Studyrecordtype;
    private javax.swing.JButton btnupdate_cate;
    private javax.swing.JButton btnupdate_dept;
    private javax.swing.JButton btnupdate_major;
    private javax.swing.JButton btnupdate_skill;
    private javax.swing.JButton btnupdate_traincourse;
    private javax.swing.JButton btnupdateemtype;
    private javax.swing.JButton btnupdatepostion;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JDesktopPane jDesktopPane3;
    private javax.swing.JDesktopPane jDesktopPane4;
    private javax.swing.JDesktopPane jDesktopPane5;
    private javax.swing.JDesktopPane jDesktopPane6;
    private javax.swing.JDesktopPane jDesktopPane7;
    private javax.swing.JDesktopPane jDesktopPane8;
    private javax.swing.JDesktopPane jDesktopPane9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable tbStudyrecordtype;
    private javax.swing.JTable tbTrainType;
    private javax.swing.JTable tbcate;
    private javax.swing.JTable tbdept;
    private javax.swing.JTable tbemtype;
    private javax.swing.JTable tbmajor;
    private javax.swing.JTabbedPane tbpall;
    private javax.swing.JTable tbposition;
    private javax.swing.JTable tbskill;
    private javax.swing.JTable tbtraincourse;
    private javax.swing.JTextField txtCate_id;
    private javax.swing.JTextField txtCate_name;
    private javax.swing.JTextField txtDept_id;
    private javax.swing.JTextField txtDept_name;
    private javax.swing.JTextField txtEmtype_id;
    private javax.swing.JTextField txtEmtype_name;
    private javax.swing.JTextField txtMajor_id;
    private javax.swing.JTextField txtMajor_name;
    private javax.swing.JTextField txtPosition_id;
    private javax.swing.JTextField txtPosition_name;
    private javax.swing.JTextField txtSkill_id;
    private javax.swing.JTextField txtSkill_name;
    private javax.swing.JTextField txtStudyrecordtype_id;
    private javax.swing.JTextField txtStudyrecordtype_name;
    private javax.swing.JTextArea txtTrainDes;
    private javax.swing.JTextField txtTrainTypeDura;
    private javax.swing.JTextField txtTrainTypeID;
    private javax.swing.JTextField txtTrainTypeName;
    private javax.swing.JTextField txtTraincourse_id;
    private javax.swing.JTextField txtTraincourse_name;
    // End of variables declaration//GEN-END:variables
}
