/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Recruitment;

import CMS.ButtonColumn;
import CMS.DB;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author panha
 */
public class frm_Interviewee extends javax.swing.JFrame {

    /**
     * Creates new form frm_Interviewee
     */
    public frm_Interviewee() {
        initComponents();
        DisplayName();
       
    }
    DB c = new DB();
    DefaultTableModel dm;
    JTextField Stid =new JTextField();

    public void AddButtonInTable(int col){
            Action delete = new AbstractAction()
            {
                public void actionPerformed(ActionEvent e)
                {
//                    JTable table = (JTable)e.getSource();
//                    int modelRow = Integer.valueOf( e.getActionCommand() );
                   // ((DefaultTableModel)table.getModel()).removeRow(modelRow);
                    int i = tbdata.getSelectedRow();
                    TableModel m = tbdata.getModel();
                    System.out.println(m.getValueAt(i, 0).toString());
                }
            };

            ButtonColumn buttonColumn = new ButtonColumn(tbdata, delete, col);
            buttonColumn.st="Study";
          //  buttonColumn.setMnemonic(KeyEvent.VK_D);
    }
    
    public void Work(int col){
            Action delete = new AbstractAction()
            {
                public void actionPerformed(ActionEvent e)
                {
//                    JTable table = (JTable)e.getSource();
//                    int modelRow = Integer.valueOf( e.getActionCommand() );
                   // ((DefaultTableModel)table.getModel()).removeRow(modelRow);
                    int i = tbdata.getSelectedRow();
                    TableModel m = tbdata.getModel();
                    System.out.println(m.getValueAt(i, 0).toString());
                }
            };

            ButtonColumn buttonColumn = new ButtonColumn(tbdata, delete, col);
            buttonColumn.st="WP";
          //  buttonColumn.setMnemonic(KeyEvent.VK_D);
    }
    
    
    private void DisplayName(){
        try {
           String sql="SELECT  Name\n" +
                       "FROM interviewees;";
        c.DisplayName(cbName, sql);
        cbName.setSelectedItem("");
        } catch (Exception e) {
        }
        
    }
    
    private void DisplayData(){
        String sql="SELECT IntervieweeId, Name, Gender, Address, Tel, Image, Status, Blocked, `Degree`, `Language`, SkillId, Dob, Email\n" +
                    "FROM interviewees WHERE Name LIKE '"+cbName.getSelectedItem().toString().trim()+"%';";
        c.showDataInTable(tbdata, sql, dm);
    }
    private void Displayall(){
         String sql="SELECT IntervieweeId, Name, Gender, Address, Tel, Image, Status, Blocked, `Degree`, `Language`, SkillId, Dob, Email\n" +
                    "FROM interviewees;";
        c.showDataInTable(tbdata, sql, dm);
    }
    
//    private void Displayid(){
//        try {
//        String st = cbName.getSelectedItem().toString();
//        String sql="SELECT IntervieweeId \n" +
//                   "FROM interviewees WHERE Name = '"+st+"';";
//        c.DisplayId(sql, Stid);
//        System.out.println(Stid.getText());
//        } catch (Exception e) {
//        }  
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbName = new javaapplication21.AutoComboBox();
        btnsearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbdata = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));

        cbName.setAutocomplete(true);
        cbName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbName.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbNamePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel1.add(cbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 210, 30));

        btnsearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 127, 30));

        tbdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbdata);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1360, 600));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search Interviewee StudyCord");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 300, 40));

        btnall.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnall.setText("Show ALL");
        btnall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnallActionPerformed(evt);
            }
        });
        jPanel1.add(btnall, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 127, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbNamePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbNamePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
       // Displayid();
    }//GEN-LAST:event_cbNamePopupMenuWillBecomeInvisible

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
       
        dm = (DefaultTableModel)tbdata.getModel();
        tbdata.setModel(dm);
        DisplayData();
        DefaultTableCellRenderer tableRenderer = new DefaultTableCellRenderer();
        tableRenderer.setHorizontalAlignment(JLabel.CENTER); //Aligning the table data centrally.
        tbdata.setDefaultRenderer(Object.class, tableRenderer);
        tbdata.setRowHeight(35);
        dm.addColumn("Study");
        dm.addColumn("WorkExperience");
        AddButtonInTable(13);
        Work(14);
        
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnallActionPerformed
        // TODO add your handling code here:
        dm = (DefaultTableModel)tbdata.getModel();
        tbdata.setModel(dm);
        Displayall();
        DefaultTableCellRenderer tableRenderer = new DefaultTableCellRenderer();
        tableRenderer.setHorizontalAlignment(JLabel.CENTER); //Aligning the table data centrally.
        tbdata.setDefaultRenderer(Object.class, tableRenderer);
        tbdata.setRowHeight(35);
        dm.addColumn("Button");
         dm.addColumn("WorkExperience");
        AddButtonInTable(13);
        Work(14);
    }//GEN-LAST:event_btnallActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Interviewee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Interviewee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Interviewee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Interviewee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Interviewee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnall;
    private javax.swing.JButton btnsearch;
    private javaapplication21.AutoComboBox cbName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbdata;
    // End of variables declaration//GEN-END:variables
}
