/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm_select_CheckIn_CheckOut;

import CA.AC;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author panha
 */
public class frm_Display_Staff_Check extends javax.swing.JFrame {
   DefaultTableModel dm;
    /**
     * Creates new form frm_Display_Staff_Check
     */
    public frm_Display_Staff_Check() {
        initComponents();
    }
    AC c = new AC();
    JTextField Stid =new JTextField();
 
    
    
    private void DisplayName(){
          if (ckEnable.isSelected()==true) {
            cbstaff.setEnabled(true);
           String sql = "SELECT  Name FROM USERINFO;";
           c.DisplayName(cbstaff, sql);
           cbstaff.setSelectedItem("");
           ckEnable.setSelected(true);
          
        }
        else
        {
            cbstaff.setEnabled(false);
            cbstaff.removeAllItems();
            ckEnable.setSelected(false);
        }
    }
    private void DisplayId(){
          try {
            String st = cbstaff.getSelectedItem().toString();
//             System.out.println(st);
              String sql = "SELECT  USERID FROM USERINFO WHERE Name = '"+st+"';";
              c.DisplayId(sql, Stid);
            System.out.println(Stid.getText());
        } catch (Exception e) {
        }
    }
    
    private void DisplayCheckTime(){
        
        
        if (dstart.getDate()==null || dend.getDate()==null) {
                JOptionPane.showMessageDialog(this,"You Should Select Date For Search ");
                return;
            }
        SimpleDateFormat formater = new SimpleDateFormat("MM/dd/yyyy");
          String ds =formater.format(dstart.getDate());
          ds="#"+ds+"#";
          String de =formater.format(dend.getDate());
          de="#"+de+"#";
        try {
            
            
            if (ckEnable.isSelected()==true) {
               
                String sql ="SELECT USERID ,`Name` , CHECKTIME ,Switch(CHECKTYPE=\"I\",\"CheckIns\",CHECKTYPE=\"O\",\"CheckOut\") AS Check FROM CHECKINOUT  JOIN USERINFO ON CHECKINOUT.USERID=USERINFO.USERID  WHERE CHECKINOUT.USERID='"+Stid.getText()+"' AND Format (CHECKINOUT.CHECKTIME,\"Short Date\") BETWEEN Format ("+ds+",\"Short Date\") AND Format ("+de+",\"Short Date\");";
                 c.showDataInTable(tbCheck, sql, dm);
            }
            else{
                
                String sql="SELECT CHECKINOUT.USERID ,`Name` , CHECKTIME ,Switch(CHECKTYPE=\"I\",\"CheckIns\",CHECKTYPE=\"O\",\"CheckOut\") AS Check FROM CHECKINOUT  JOIN USERINFO ON CHECKINOUT.USERID=USERINFO.USERID  WHERE  Format (CHECKINOUT.CHECKTIME,\"Short Date\") BETWEEN Format ("+ds+",\"Short Date\") AND Format ("+de+",\"Short Date\");";
                c.showDataInTable(tbCheck, sql, dm);
            }
        } catch (Exception e) {
            e.getMessage();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbCheck = new controls.SubJTable();
        btnDisplay = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dend = new org.jdesktop.swingx.JXDatePicker();
        dstart = new org.jdesktop.swingx.JXDatePicker();
        cbstaff = new javaapplication21.AutoComboBox();
        ckEnable = new javax.swing.JCheckBox();
        btnSent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tbCheck.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbCheck);

        btnDisplay.setText("Display");
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("To");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("From");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("From");

        cbstaff.setAutocomplete(true);
        cbstaff.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbstaff.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbstaffItemStateChanged(evt);
            }
        });
        cbstaff.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cbstaffPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cbstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbstaffActionPerformed(evt);
            }
        });

        ckEnable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckEnable.setText("Enable");
        ckEnable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckEnableActionPerformed(evt);
            }
        });

        btnSent.setText("Sent");
        btnSent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ckEnable, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dstart, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dend, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSent, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dstart, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ckEnable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dend, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSent, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           
            cbstaff.setEnabled(false);
        
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void cbstaffItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbstaffItemStateChanged
      
       
            
       
// TODO add your handling code here:
    }//GEN-LAST:event_cbstaffItemStateChanged

    private void cbstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbstaffActionPerformed
        
       
        // TODO add your handling code here:
    }//GEN-LAST:event_cbstaffActionPerformed

    private void ckEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckEnableActionPerformed
            DisplayName();
      
        // TODO add your handling code here:
    }//GEN-LAST:event_ckEnableActionPerformed

    private void cbstaffPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cbstaffPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
            DisplayId();
    }//GEN-LAST:event_cbstaffPopupMenuWillBecomeInvisible

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
        DisplayCheckTime();
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnSentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Display_Staff_Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Display_Staff_Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Display_Staff_Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Display_Staff_Check.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Display_Staff_Check().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnSent;
    private javaapplication21.AutoComboBox cbstaff;
    private javax.swing.JCheckBox ckEnable;
    private org.jdesktop.swingx.JXDatePicker dend;
    private org.jdesktop.swingx.JXDatePicker dstart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private controls.SubJTable tbCheck;
    // End of variables declaration//GEN-END:variables
}
